In [131]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os.path
import itertools
import datetime

from IPython.display import display
pd.options.display.max_columns = None
above = '../../../'
# val_file = above + 'assessment_og.pkl'
# valuation = pd.read_pickle(val_file)
inner_file = above + 'merged-sales-valuation-macroeconomic.pkl'
inner = pd.read_pickle(inner_file)

In [132]:
moon = inner
moon.shape

(340540, 80)

In [133]:
hmm = pd.read_pickle(above + 'merged-sales-valuation-macroeconomic_pg.pkl')
hmm.drop(["S_easement"], axis=1, inplace=True)
# hmm.to_csv(above + 'merged-sales-valuation-macroeconomic_pg.csv')

In [138]:
# Whats the mean and median difference
print(f' Mean difference is {np.round(hmm["S_sale_price"].mean() - hmm["v_fullval"].mean(), 0)}')
print(f' Median difference is {hmm["S_sale_price"].median() - hmm["v_fullval"].median()}')

 Mean difference is -6338051.0
 Median difference is -37000.0

In [71]:
hmm.columns == moon.columns

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True])

In [118]:
hmm.iloc[[1,2], :]

,S_borough,S_neighborhood,S_building_class_category,S_block,S_lot,S_address,S_apt_number,S_zipcode,S_residential_units,S_commercial_units,S_total_units,S_land_sqft,S_gross_sqft,S_year_built,S_tax_class_at_sale,S_building_class_at_sale,S_sale_price,S_sale_date,S_apt_2,S_sale_price_per_unit,bbl,year,v_bble,v_boro,v_block,v_lot,v_owner,v_bldgcl,v_taxclass,v_ltfront,v_ltdepth,v_ext,v_stories,v_fullval,v_avland,v_avtot,v_staddr,v_postcode,v_bldfront,v_blddepth,v_avland2,v_avtot2,v_latitude,v_longitude,v_community_board,v_council_district,v_census_tract,v_bin,v_nta,v_new_georeferenced_column,S_sale_month,S_sale_year,YEAR,MONTH,10Yr Treasury Constant Maturity Rate,30Yr Fixed Rate Mortgage Avg in US,Case-Shiller NY Home Price Index,Case-Shiller US National Home Price Index,Consumer Price Index,Core CPI,Effective Fed Funds Rate,Inflation Rate,Population Level,Real Gross Domestic Product,SP500 Index,Unemployment Rate,US Real Median Household Income,10Yr Treasury Constant Maturity Rate %Chg,30Yr Fixed Rate Mortgage Avg in US %Chg,Case-Shiller NY Home Price Index %Chg,Case-Shiller US National Home Price Index %Chg,Consumer Price Index %Chg,Core CPI %Chg,Effective Fed Funds Rate %Chg,Inflation Rate %Chg,Population Level %Chg,Real Gross Domestic Product %Chg,SP500 Index %Chg,Unemployment Rate %Chg,US Real Median Household Income %Chg
1,2,BAYCHESTER,01 ONE FAMILY HOMES,04715,0022,1156 EAST 221 STREET,,10469.0,1.0,0.0,1.0,1842.0,1744.0,1950.0,1,A5,180000,2012-12-19,None,180000.0,2047150022,2012/13,2047150022,2,04715,0022,HAMILTON INA,A5,1,18,99,NaN,3.0,313000,12420,18780,1156 EAST 221 STREET,10469.0,18,35,NaN,NaN,40.880741,-73.849524,212.0,12.0,386.0,2060039.0,Eastchester-Edenwald-Baychester,POINT (-73.849524 40.880741),12,2012,2012,12,1.722381,3.345,162.70468,145.505,231.221,231.725,0.164516,1.515208,315258.0,16335.022,1422.49381,7.9,58738.0,0.041572,-0.002088,0.001268,0.006335,-0.000121,0.001708,0.023959,-0.032177,0.000527,0.002944,0.020181,0.025974,0.002834
2,2,BAYCHESTER,01 ONE FAMILY HOMES,04715,0056,3840 LACONIA AVENUE,,10469.0,1.0,0.0,1.0,2320.0,1690.0,1950.0,1,A9,290000,2012-12-18,None,290000.0,2047150056,2012/13,2047150056,2,04715,0056,CLAUDE RICHARDSON,A9,1,19,99,NaN,3.0,294000,12840,17640,3840 LACONIA AVENUE,10469.0,18,35,NaN,NaN,40.881242,-73.851273,212.0,12.0,386.0,2060062.0,Eastchester-Edenwald-Baychester,POINT (-73.851273 40.881242),12,2012,2012,12,1.722381,3.345,162.70468,145.505,231.221,231.725,0.164516,1.515208,315258.0,16335.022,1422.49381,7.9,58738.0,0.041572,-0.002088,0.001268,0.006335,-0.000121,0.001708,0.023959,-0.032177,0.000527,0.002944,0.020181,0.025974,0.002834

In [152]:
hmm.groupby(['bbl','year']).bbl.size()

bbl         year
1000070038  2015/16    1
1000110010  2012/13    1
1000110014  2013/14    2
            2015/16    1
            2017/18    1
                      ..
5080500017  2014/15    1
5080500019  2015/16    1
5080500031  2017/18    1
5080500060  2012/13    2
5080500083  2017/18    1
Name: bbl, Length: 278040, dtype: int64

In [151]:
moon.groupby(['bbl','year']).bbl.size()

bbl         year
1000070038  2015/16    1
1000110014  2013/14    2
            2015/16    1
            2017/18    1
            2018/19    2
                      ..
5080500017  2014/15    1
5080500019  2015/16    1
5080500031  2017/18    1
5080500060  2012/13    1
5080500083  2017/18    1
Name: bbl, Length: 261004, dtype: int64

In [163]:
twetwev_hmm, twetwev_moon = hmm[hmm.year == '2012/13'], moon[moon.year == '2012/13']
twetwev_hmm.S_sale_date.isin(twetwev_moon.S_sale_date).sum()

23708

In [168]:
twetwev_hmm.S_sale_date.min()

Timestamp('2012-07-02 00:00:00')

In [162]:
47780-29995

17785

In [129]:
lost_data = hmm.iloc[().index, :]
lost_data

,S_borough,S_neighborhood,S_building_class_category,S_block,S_lot,S_address,S_apt_number,S_zipcode,S_residential_units,S_commercial_units,S_total_units,S_land_sqft,S_gross_sqft,S_year_built,S_tax_class_at_sale,S_building_class_at_sale,S_sale_price,S_sale_date,S_apt_2,S_sale_price_per_unit,bbl,year,v_bble,v_boro,v_block,v_lot,v_owner,v_bldgcl,v_taxclass,v_ltfront,v_ltdepth,v_ext,v_stories,v_fullval,v_avland,v_avtot,v_staddr,v_postcode,v_bldfront,v_blddepth,v_avland2,v_avtot2,v_latitude,v_longitude,v_community_board,v_council_district,v_census_tract,v_bin,v_nta,v_new_georeferenced_column,S_sale_month,S_sale_year,YEAR,MONTH,10Yr Treasury Constant Maturity Rate,30Yr Fixed Rate Mortgage Avg in US,Case-Shiller NY Home Price Index,Case-Shiller US National Home Price Index,Consumer Price Index,Core CPI,Effective Fed Funds Rate,Inflation Rate,Population Level,Real Gross Domestic Product,SP500 Index,Unemployment Rate,US Real Median Household Income,10Yr Treasury Constant Maturity Rate %Chg,30Yr Fixed Rate Mortgage Avg in US %Chg,Case-Shiller NY Home Price Index %Chg,Case-Shiller US National Home Price Index %Chg,Consumer Price Index %Chg,Core CPI %Chg,Effective Fed Funds Rate %Chg,Inflation Rate %Chg,Population Level %Chg,Real Gross Domestic Product %Chg,SP500 Index %Chg,Unemployment Rate %Chg,US Real Median Household Income %Chg
1,2,BAYCHESTER,01 ONE FAMILY HOMES,04715,0022,1156 EAST 221 STREET,,10469.0,1.0,0.0,1.0,1842.0,1744.0,1950.0,1,A5,180000,2012-12-19,None,180000.0,2047150022,2012/13,2047150022,2,04715,0022,HAMILTON INA,A5,1,18,99,NaN,3.0,313000,12420,18780,1156 EAST 221 STREET,10469.0,18,35,NaN,NaN,40.880741,-73.849524,212.0,12.0,386.0,2060039.0,Eastchester-Edenwald-Baychester,POINT (-73.849524 40.880741),12,2012,2012,12,1.722381,3.3450,162.704680,145.505,231.221,231.725,0.164516,1.515208,315258.0,16335.022000,1422.49381,7.9,58738.0,0.041572,-0.002088,0.001268,0.006335,-0.000121,0.001708,0.023959,-0.032177,0.000527,0.002944,0.020181,0.025974,0.002834
6,2,BAYCHESTER,01 ONE FAMILY HOMES,04803,0043,2720 GUNTHER AVENUE,,10469.0,1.0,0.0,1.0,2470.0,1088.0,1955.0,1,A5,214120,2012-12-11,None,214120.0,2048030043,2012/13,2048030043,2,04803,0043,FEDERAL NATIONAL MORT,A5,1,26,95,NaN,2.0,231000,12480,13860,2720 GUNTHER AVENUE,10469.0,16,34,NaN,NaN,40.866149,-73.836834,212.0,12.0,356.0,2062794.0,Eastchester-Edenwald-Baychester,POINT (-73.836834 40.866149),12,2012,2012,12,1.722381,3.3450,162.704680,145.505,231.221,231.725,0.164516,1.515208,315258.0,16335.022000,1422.49381,7.9,58738.0,0.041572,-0.002088,0.001268,0.006335,-0.000121,0.001708,0.023959,-0.032177,0.000527,0.002944,0.020181,0.025974,0.002834
16,2,BAYCHESTER,02 TWO FAMILY HOMES,04978,0052,4077 ELY AVENUE,,10466.0,2.0,0.0,2.0,1900.0,2695.0,1955.0,1,B1,280000,2012-12-04,None,140000.0,2049780052,2012/13,2049780052,2,04978,0052,BEAZER HAROLD H,B1,1,20,95,G,2.0,430000,14561,22768,4077 ELY AVENUE,10466.0,20,49,NaN,NaN,40.891470,-73.845980,212.0,12.0,426.0,2067323.0,Woodlawn-Wakefield,POINT (-73.84598 40.89147),12,2012,2012,12,1.722381,3.3450,162.704680,145.505,231.221,231.725,0.164516,1.515208,315258.0,16335.022000,1422.49381,7.9,58738.0,0.041572,-0.002088,0.001268,0.006335,-0.000121,0.001708,0.023959,-0.032177,0.000527,0.002944,0.020181,0.025974,0.002834
21,2,BEDFORD PARK/NORWOOD,02 TWO FAMILY HOMES,03343,0146,3341 PERRY AVENUE,,10467.0,2.0,0.0,2.0,3250.0,4113.0,1915.0,1,B2,265000,2012-12-28,None,132500.0,2033430146,2012/13,2033430146,2,03343,0146,HUNTER JOHN,B2,1,25,138,NaN,2.5,514000,12250,20377,3341 PERRY AVENUE,10467.0,21,60,NaN,NaN,40.878256,-73.874651,207.0,11.0,423.0,2018196.0,Norwood,POINT (-73.874651 40.878256),12,2012,2012,12,1.722381,3.3450,162.704680,145.505,231.221,231.725,0.164516,1.515208,315258.0,16335.022000,1422.49381,7.9,58738.0,0.041572,-0.002088,0.001268,0.006335,-0.000121,0.001708,0.023959,-0.032177,0.000527,0.002944,0.020181,0.025974,0.002834
29,2,BEDFORD PARK/NORWOOD,10 COOPS - ELEVATOR APARTMENTS,03311,0044,3201 GRAND CONCOURSE,,10468.0,0.0,0.0,0.0,0.0,0.0,1963.0,2,D4,125000,2012-12-13,1D,inf,2033110044,2012/13,2033110044,2,03311,0044,3201 GRAND CONCOURSE,D4,2,138,199,NaN,6.0,3388000,71100,1524600,3201 GRAND CONCOURSE,10468.0,100,170,71100.0,1481310.0,40.876857,-73.885545,207.0,11.0,411.0,2017340.0,Bedford Park-Fordham North,POINT (-73.885545 40.876857),12,2012,2012,12,1.722381,3.3450,162.704680,145.505,231.221,231.725,0.164516,1.515208,315258.0,16335.022000,1422.49381,7.9,58738.0,0.041572,-0.002088,0.001268,0.006335,-0.000121,0.001708,0.023959,-0.032177,0.000527,0.002944,0.020181,0.025974,0.002834
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
364607,5,WOODROW,01 ONE FAMILY DWELLINGS,07355,0008,117 CHURCHILL AVENUE,NaN,10309.0,1.0,0.0,1.0,2392.0,2160.0,2001.0,1,A5,635000,2019-06-11,None,635000.0,5073550008,2018/19,5073550008,5,07355,0008,"MEYLER, CAGNEY",A5,1,26,92,NaN,3.0,533000,5216,21720,117 CHURCHILL AVENUE,10309.0,16,45,NaN,NaN,40.529645,-74.221113,503.0,51.0,226.0,5133689.0,Charleston-Richmond Valley-Tottenville,POINT (-74.221113 40.529645),6,2019,2019,6,2.074000,3.8025,200.959815,209.057,255.402,262.925,2.377667,1.812210,328404.0,19101.362333,2890.16600,3.7,68703.0,-0.132849,-0.066184,-0.001691,0.001696,0.000921,0.002769,-0.005563,0.000000,0.000417,0.002119,0.012864,0.027778,0.000000
364608,5,WOODROW,02 TWO FAMILY DWELLINGS,07013,0053,100 MARISA CIRCLE,NaN,10309.0,2.0,0.0,2.0,3773.0,3096.0,1984.0,1,B2,855000,2019-06-17,None,427500.0,5070130053,2018/19,5070130053,5,07013,0053,ANTHONY BARTOLONE,B2,1,41,90,G,2.0,755000,11428,42294,100 MARISA CIRCLE,10309.0,26,50,NaN,NaN,40.538225,-74.215576,503.0,51.0,20803.0,5085635.0,Rossville-Woodrow,POINT (-74.215576 40.538225),6,2019,2019,6,2.074000,3.8025,200.959815,209.057,255.402,262.925,2.377667,1.812210,328404.0,19101.362333,2890.16600,3.7,68703.0,-0.132849,-0.066184,-0.001691,0.001696,0.000921,0.002769,-0.005563,0.000000,0.000417,0.002119,0.012864,0.027778,0.000000
364609,5,WOODROW,02 TWO FAMILY DWELLINGS,07014,0218,31 MARVIN ROAD,NaN,10309.0,2.0,0.0,2.0,5360.0,2448.0,1980.0,1,B2,870000,2019-06-28,None,435000.0,5070140218,2018/19,5070140218,5,07014,0218,ANA BEHNAM BAKHSH,B2,1,40,133,NaN,2.0,715000,11993,37944,31 MARVIN ROAD,10309.0,28,48,NaN,NaN,40.536490,-74.217067,503.0,51.0,20803.0,5085703.0,Rossville-Woodrow,POINT (-74.217067 40.53649),6,2019,2019,6,2.074000,3.8025,200.959815,209.057,255.402,262.925,2.377667,1.812210,328404.0,19101.362333,2890.16600,3.7,68703.0,-0.132849,-0.066184,-0.001691,0.001696,0.000921,0.002769,-0.005563,0.000000,0.000417,0.002119,0.012864,0.027778,0.000000
364610,5,WOODROW,02 TWO FAMILY DWELLINGS,07105,0151,20 APRICOT COURT,NaN,10309.0,2.0,0.0,2.0,4836.0,1832.0,2017.0,1,B9,778961,2019-06-10,None,389480.5,5071050151,2018/19,5071050151,5,07105,0151,NaN,B9,1,0,0,NaN,NaN,242000,4155,4155,20 APRICOT COURT,10309.0,0,0,NaN,NaN,40.542016,-74.222582,503.0,51.0,226.0,5000000.0,Charleston-Richmond Valley-Tottenville,POINT (-74.222582 40.542016),6,2019,2019,6,2.074000,3.8025,200.959815,209.057,255.402,262.925,2.377667,1.812210,328404.0,19101.362333,2890.16600,3.7,68703.0,-0.132849,-0.066184,-0.001691,0.001696,0.000921,0.002769,-0.005563,0.000000,0.000417,0.002119,0.012864,0.027778,0.000000
364611,5,WOODROW,02 TWO FAMILY DWELLINGS,07316,0084,57 DARNELL LANE,NaN,10309.0,2.0,0.0,2.0,2311.0,1500.0,1995.0,1,B2,620000,2019-06-20,None,310000.0,5073160084,2018/19,5073160084,5,07316,0084,SALVATORE ANNARUMMA,B2,1,26,88,NaN,2.0,518000,6690,27072,57 DARNELL LANE,10309.0,16,44,NaN,NaN,40.536003,-74.223213,503.0,51.0,226.0,5130720.0,Charleston-Richmond Valley-Tottenville,POINT (-74.223213 40.536003),6,2019,2019,6,2.074000,3.8025,200.959815,209.057,255.402,262.925,2.377667,1.812210,328404.0,19101.362333,2890.16600,3.7,68703.0,-0.132849,-0.066184,-0.001691,0.001696,0.000921,0.002769,-0.005563,0.000000,0.000417,0.002119,0.012864,0.027778,0.000000

In [101]:
len(~(hmm_sales_dates).isin(moon.S_sale_date))

346827

In [155]:
len((hmm.bbl+hmm.year).isin(moon.bbl + moon.year))

364612

In [106]:
len(hmm[(hmm.bbl+hmm.year).isin(moon.bbl + moon.year)])

346827

In [108]:
hmm_sales_dates = hmm[(hmm.bbl+hmm.year).isin(moon.bbl + moon.year)].S_sale_date

In [83]:
346827 - 340540

6287

In [43]:
moon.columns[18:21]

Index(['bbl', 'bbl_block', 'bbl_lot'], dtype='object')

In [49]:
moon.S_sale_price_per_unit

AttributeError: 'DataFrame' object has no attribute 'S_sale_price_per_unit'

In [42]:
hmm.columns[18:21]

Index(['S_apt_2', 'S_sale_price_per_unit', 'bbl'], dtype='object')

In [62]:
364612 - 12808

351804

In [ ]:
pd_readpickl(merged-sales-valuation-dem.pkl')